{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: {
  imports = [
    inputs.sops-nix.homeManagerModules.sops
  ];

  options.secrets = {
    apiKeysFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = ../../secrets/api-keys.yaml;
      description = "Path to the API keys file. Set to null to disable loading API keys.";
    };

    apiKeysEnable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to automatically load all API keys from the api-keys file into environment variables";
    };
  };

  config = let
    apiKeysFile = config.secrets.apiKeysFile;
    apiKeysExists = apiKeysFile != null && builtins.pathExists apiKeysFile;
  in
    lib.mkIf (apiKeysExists && config.secrets.apiKeysEnable) {
      home.packages = [pkgs.yq];

      sops = {
        age.keyFile = lib.mkDefault "${config.home.homeDirectory}/.config/sops/age/keys.txt";
        defaultSopsFormat = "yaml";
        validateSopsFiles = true;

        # Mount entire api-keys.yaml file as-is using empty key
        secrets.api-keys = {
          sopsFile = apiKeysFile;
          key = ""; # Empty key = entire file mounted as-is
        };
      };

      # Generate a standalone, sourceable file with the decrypted API keys as
      # env exports. Works regardless of whether programs.zsh is managed by
      # home-manager (darwin-minimal does NOT enable programs.zsh — that lives
      # in shell.nix). Source it from ~/.zshrc or any shell rc:
      #   [[ -f ~/.config/zsh/secrets.zsh ]] && source ~/.config/zsh/secrets.zsh
      home.file.".config/zsh/secrets.zsh".text = ''
        # auto-generated by secrets.nix — exports sops-decrypted API keys
        if [[ -f "${config.sops.secrets.api-keys.path}" ]]; then
          eval $(${pkgs.yq}/bin/yq -r '
            to_entries | .[] |
            select(.key != "sops") |
            "export " + (.key | ascii_upcase) + "=" + (.value | @sh)
          ' "${config.sops.secrets.api-keys.path}")
        fi
      '';

      # Also wire it into hm-managed zsh when shell.nix is imported (linux/desktop).
      programs.zsh.initContent = lib.mkAfter ''
        [[ -f ~/.config/zsh/secrets.zsh ]] && source ~/.config/zsh/secrets.zsh
      '';
    };
}
